# Project identification
sonar.projectKey=subingeorge-123_Smart_Expense_Manager
sonar.organization=subingeorge-123

# Source code
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=.github/workflows/**,tests/**,migrations/**,*.md

# Test coverage
sonar.python.coverage.reportPaths=tests/coverage.xml